#!/bin/bash

STYLE=$(git config --get hooks.clangformat.style)
if [ -n "${STYLE}" ] ; then
  STYLEARG="-style=${STYLE}"
else
  STYLEARG=""
fi

FILES_POLISHED=0

check_format_file() {
  file="${1}"
  if [ -f $file ]; then
    # clang-format -i ${STYLEARG} ${1}
    TEMP=`mktemp`
    clang-format ${STYLEARG} ${1} > $TEMP
    diff -q ${1} ${TEMP} &> /dev/null
    ret=$?
    rm ${TEMP}
    if [ "$ret" -ne 0 ] ; then
      echo clang-format: File "${1}" is NOT polished
      FILES_POLISHED=1
    fi
    # git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on source files does not modify commited sources"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
      check_format_file "${file}"
    done
    if [ "$FILES_POLISHED" -ne 0 ] ; then
      echo "Try polishing files using clang-format prior to git commit"
      echo -e "\nCOMMIT ABORTED: file(s) require(s) polishing\n"
    fi
    ;;
esac

exit $FILES_POLISHED
