#
#  Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without modification,
#  are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its contributors
#     may be used to endorse or promote products derived from this software without
#     specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
#  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

name: Branch Name Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_branch_name:
    runs-on: ubuntu-latest  # Use the default GitHub-hosted runner with Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check branch name using Bash
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        USER: ${{ github.actor }}
      run: |
        FORBIDDEN_NAMES=("amd-main" "amd-dev" "RC" "AOCL")
        for str in "${FORBIDDEN_NAMES[@]}"; do
          if [[ "$BRANCH_NAME" =~ $str ]]; then
            echo "Error: Branch name '$BRANCH_NAME' contains forbidden string '$str'."
            exit 1
          fi
        done
        echo "Branch name '$BRANCH_NAME' is valid."
      shell: bash  # Use the default Linux shell
